### ISSUE TITLE
[Feature Request] Tag support for project layout

### ISSUE THREAD

**Issue by imswebra** [hydecorp/hydejack#139]
I'm wondering about the possibility of simple ```tag``` support for the ```project``` layout, in the same vein as the functionality on ```posts```; a simple addition in the front matter which links to a project view restricted to the same tags.

To be clear, this functionality exists already using multiple collections with multiple project pages, but none are as easy and streamlined as the tag system. Ideally I would like to be be able to keep all projects in the ```_projects``` folder and then just add tags to the front matter in addition to the one-time file creation in ```_featured_tags```.

This could also provide a framework for implementing shared tag pages, where both projects and posts belonging to the same tag could be displayed.

**Comment by qwtel** [comment]
I agree that this would be useful but I currently don't have capacity to implement this.

**Comment by qwtel** [comment]
I've decided against implementing this, since it's already possible to do virtually the same by using Jekyll collections. Those familiar with Jekyll should be able to figure this out via the Jekyll docs and reading Hydejack's source (specifically the project layout). 

Keeping this issue open until I write documentation for this feature. I kinda forgot that I already implemented this.

**Comment by qwtel** [comment]
The docs in v9 have been updated with instructions to add multiple projects collections
