### ISSUE TITLE
The projects website doesn't works on Github pages, but works fine locally.

### ISSUE THREAD

**Issue by hellochick** [hydecorp/hydejack#170]
I bought the Pro version, and I tried to push it to my Github pages. 

Everything looks fine when running locally, however, the website of the project turns into a blank when running in Github pages. 
Here is my [website](https://hellochick.github.io/
), the situation occurs when I click the projects button in the sidebar.

Could someone help me? I am new to Jekyll, thanks a lot.

---
Update:

FYI, If I pushed the non-modified repository of Hydejack-Pro onto Github-page, it seems that the projects site will turn into a blank, too.

**Comment by qwtel** [comment]
I don't think anybody else is experiencing this, so it's most likely related to content. One thing that has tripped me up in the past is html comments `<!---` `-->`  that sometimes mess with the minify html template. Since the HTML isn't minified locally (unless you run with `JEKYLL_ENV=production`) this would explain why it only occurs on GitHub Pages.

**Comment by felixnie** [comment]
Same problem. Using v9.

**Comment by medeiros** [comment]
Same issue here. I bought the PRO version, and it works perfectly locally, but it does not work on Github.
My website is medeiros.github.io. 

I added TravisCI to be able to see the internal erros - and there was erros indeed. First, In the gemfile, I had to change the gem "jekyll", "~> 4.1" to "3.9.0" (since 4.1 is unsupported in Github, according to https://pages.github.com/versions/). After that, TravisCI finished without any compile errors, but the pages are still not rendered properly. If i hit https://medeiros.github.io/blog/ , the HTTP Status code is 200, but the page is blank. If I hit the main page (https://medeiros.github.io/, it only shows the text that I set in index.md file, but no other information is rendered).

I suspect that the problem is related to the local theme #jekyll-theme-hydejack (because I changed to the "remote_theme: hydecorp/hydejack@v9" in _config.yml file and it worked - however, using a non-PRO remote theme). I believe that, for some reason, Github is denying the use of #jekyll-theme-hydejack  as a gem.

**Comment by LazyRen** [comment]
To @medeiros.
As far as I know, you should not use `theme:` or `remote_theme:` under `_config.yml` for the github pages.<br>
If you look newly upgraded pro-9.0.5, there is a `starter-kit-gh-pages`. If you have not changed much, I recommend you to use it.<br>
Other wise, just comment `remote_theme: medeiros/jekyll-theme-hydejack` part from your `_config.yml` and see if it works.

**Comment by medeiros** [comment]
@LazyRen , thanks for your quick response.
The version is pro-9.0.4, unfortunately. And I removed the `remote_theme:` attribute, and keep only the `theme:jekyll-theme-hydejack` attribute (reverting back do the default), with no luck.
I'm trying to figure this out: if `theme:` is not valid in `_config.yml` for GitHub pages, how can the page actually use this theme, since it is not a default GitHub Pages theme, but have to be set somehow?

**Comment by LazyRen** [comment]
Try to remove `theme:` also from `_config.yml`. I'm not 100% sure about how jekyll works, but it seems it reads blog theme from the local files from the root.

**Comment by medeiros** [comment]
In this case, the behavior is the same, both locally and in GitHub: only main page, style.css and anchor.min.js are loaded.

And some warning started to be generated:
`
Configuration file: /home/travis/build/medeiros/medeiros.github.io/_config.yml
            Source: /home/travis/build/medeiros/medeiros.github.io
       Destination: /home/travis/build/medeiros/medeiros.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
     Build Warning: Layout 'grid' requested in _featured_categories/distributedarchitecture.md does not exist.
     Build Warning: Layout 'grid' requested in _featured_categories/example.md does not exist.
     Build Warning: Layout 'grid' requested in _featured_categories/infrastructure.md does not exist.
     Build Warning: Layout 'grid' requested in _featured_categories/kafka.md does not exist.
     Build Warning: Layout 'grid' requested in _featured_categories/linux.md does not exist.
     Build Warning: Layout 'grid' requested in _featured_categories/misc.md does not exist.
     Build Warning: Layout 'grid' requested in _featured_categories/snippets.md does not exist.
     Build Warning: Layout 'project' requested in _projects/kafka-connect-covid19api.md does not exist.
     Build Warning: Layout 'project' requested in _projects/kafka-streams-covid19api.md does not exist.
     Build Warning: Layout 'not-found' requested in 404.md does not exist.
     Build Warning: Layout 'blog' requested in blog/index.html does not exist.
     Build Warning: Layout 'offline' requested in offline.md does not exist.
     Build Warning: Layout 'grid' requested in posts.md does not exist.
     Build Warning: Layout 'projects' requested in projects.md does not exist.
     Build Warning: Layout 'resume' requested in resume.md does not exist.
     Build Warning: Layout 'blog' requested in blog/2/index.html does not exist.`

**Comment by LazyRen** [comment]
You are missing `_layout` folder.
Move all the folders from `#jekyll-theme-hydejack` to the `root` folder.

**Comment by medeiros** [comment]
Thanks for your help, @LazyRen. It worked.

Just for the sake of documentation, I had to perform the following actions for pro-9.0.4 to work on GitHub Pages:

- _config.yaml: 
  - remove the attributes `#theme: jekyll-theme-hydejack` and `#remote_theme: hydecorp/hydejack@v9` (ssems not to work with GitHub Pages)
- Gemfile:
   - change the jekyll version from `~> 4.1` to `~> 3.9.0` (to be compatible with https://pages.github.com/versions/)
   - remove the line `gem "jekyll-theme-hydejack", path: "./#jekyll-theme-hydejack"` (it is unnecessary, since the theme is no longer used as a referenced gem file)
- #jekyll-theme-hydejack:
  - move the following directories to the root of the repository:
    -  _layouts
    - _includes
    - _sass
    - assets

Hope it helps someone with the same issue.

**Comment by bopoh13** [comment]
@medeiros 
1. The Github Pages does not use the file `Gemfile` from the REPO (at the beginning of 2019 it was like this).
2. In the root REPO, in addition to the configuration file `_config.yml`, the folders `assets`, `_layouts` no needed.
``` yml
remote_theme: hydecorp/hydejack
# the rest from the config file as

plugins:
  - jekyll-remote-theme
```
