### ISSUE TITLE
jekyll 4 testing?

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#193]
Has anyone tested with jekyll v4? If so, what have you found? Any blockers?

**Comment by qwtel** [comment]
Hi, I have a development version that works with v4 (the upgrade is very much worth it, build speeds are much improved). Unfortunately I can't remember the issues I ran into, but it was mostly smooth. You might have to disable some plugins that haven't been updated to v4.

**Comment by shawnyeager** [comment]
Thanks. I’ll fire up a branch, and give it a try.

**Comment by shawnyeager** [comment]
Hey, @qwtel. Any updates on pushing a Jekyll 4-ready build?

**Comment by qwtel** [comment]
Hey, I have a semi-functional version but I've never published it because there are a number of problems:

* The `config.yml` file is included by default which could override settings / break existing builds
* The math solution no longer works. I have a new solution for v9, but it's a pretty big change so I'm reluctant to include it in v8.

Long story short, I'll likely not update v8 to Jekyll 4.
