### ISSUE TITLE
Dark theme text color problem

### ISSUE THREAD

**Issue by natashache** [hydecorp/hydejack#199]
Currently the post/project title text color and hyperlink text color default to the theme color in both light and dark mode. This is a problem because not that many colors can work well on both light and dark backgrounds. 

Here's a screenshot of my blog in light mode:
![Screenshot 2020-01-13 19 24 56](https://user-images.githubusercontent.com/19754530/72303425-39dd5b80-363b-11ea-952b-06bf54c5a1c4.png)
And in dark mode:
![Screenshot 2020-01-13 19 25 07](https://user-images.githubusercontent.com/19754530/72303443-495ca480-363b-11ea-8561-416439936fb7.png)

@qwtel Could you just use the light gray text color for title and hyperlink texts under dark mode, same as the rest of the texts? How can I change this manually?

**Comment by qwtel** [comment]
Yes, sadly the selection of accent colors is very limited due to dark mode. The only solutions right now is to either pick a color that works well in both cases, or disable dark mode. 

In an upcoming version I'm going to change the link style so that readability won't depend on the accent color, but picking a color that works with both remains the best solution.

**Comment by qwtel** [comment]
This should be resolved now with the new link style in v9
