### ISSUE TITLE
Safari on Mac and iOS TOC snaps to link vs a scroll effect

### ISSUE THREAD

**Issue by brainomite** [hydecorp/hydejack#220]
When using a page with a TOC on Chrome or Firefox for Mac, when a TOC item is clicked, we get a nice scroll down effect to the appropriate location. This is beautiful!

However, when using Safari on Mac OSx or on iOS, when you click a TOC link, it just jumps to the location, no pleasant scroll effect. Can you fix this?

**Comment by qwtel** [comment]
This is due to WebKit not supporting [smooth scrolling](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior)

In a pervious version of Hydejack I've shipped a [polyfill](https://github.com/iamdustan/smoothscroll), but it created artefacts when combined with `position: fixed` elements, so I've removed it.
