### ISSUE TITLE
ToC not sticky

### ISSUE THREAD

**Issue by alpha-src** [hydecorp/hydejack#246]
#### Hi i'm currently using hydejack theme for my github pages! (https://alpha-src.github.io)

If you visit my page, you can see `ToC` is not moving. I set my `no_break_layout` to `false`, but it's still not moving. <br>

How can I fix this problem? Thanks

**Comment by LazyRen** [comment]
![Screen Shot 2021-01-13 at 12 35 19 PM](https://user-images.githubusercontent.com/8989837/104403435-d82c3600-559b-11eb-8865-902ebfe64675.png)

By `moving ToC` do you mean dynamic Table of Contents like screenshot?
If so, your blog works perfectly. Maybe you should check it with larger screen.

As far as I know `no_break_layout` works for `code section` & `table`.
Use `no_toc` to control behavior of dynamic ToC.

```yaml
# Set to `true` to disable the dynamic Table of Contents on large screens.
no_toc:              false
```

**Comment by alpha-src** [comment]
Thanks for helping me out. I guess my screen is not big enough. I will close this issue!

**Comment by LazyRen** [comment]
It seems I've misunderstood the question. The problem was Table of Contents of [Hydejack Starter Kit](https://hydecorp.github.io/hydejack-starter-kit/) is not sticked to the display. Which should be done by adding `affix` class to the `markdown-toc` object by Javascript toc-hydejack.js.

I kindly asking you @qwtel is this intentional behavior since some features are PRO version exclusive?
If not, I'd like this issue be opened again.

Thank you.

**Comment by qwtel** [comment]
> PRO version exclusive

Yes, the sticky ToC is currently a PRO exclusive.
