### ISSUE TITLE
Fix `Uncaught TypeError: Cannot destructure property 'protocol' of 'e' as it is null.     at R (vendors~push-state-hydejack-9.1.5.js:14:1496)`

### ISSUE THREAD

**Issue by LazyRen** [hydecorp/hydejack#295]
This error happens when you click the empty space of the blog (thus nothing happens). The sideeffect of the error is close to none - it only prints error log on console - but it's still distracting.

Simply wrapping the problematic function with `if(e)` statement seems to solve the issue. LazyRen/LazyRen.github.io@42454b7f2bacb3132188bd852cf9aed45bc02f51

```default
Uncaught TypeError: Cannot destructure property 'protocol' of 'e' as it is null.
    at R (vendors~push-state-hydejack-9.1.5.js:14:1496)
    at HTMLHtmlElement.<anonymous> (vendors~push-state-hydejack-9.1.5.js:14:15908)
```

I won't create a PR as it seems you don't take any PR. #244

**Comment by qwtel** [comment]
I have a fix for this, will release soon. I have a whole checklist to go through for each release, so I tend to not do it for single issues. 

Unfortunately, taking PRs is a bit tricky, since this repo is not the one I use for development. I have a private one that includes the PRO related code. I've sent you an invite.

**Comment by LazyRen** [comment]
Oh thank you @qwtel!
I just wanted to let you know the issue just in case.

As always, thank you for great theme 👍🏻.
I'll close this issue :)
